In [28]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.datasets import load_boston
df=load_boston() #data frame

df.keys() #returns all keys of dataset dictionary
print(df.data) #INFO about datset

boston=pd.DataFrame(df.data,columns=df.feature_names) #df is tabular rep of entire data
boston.head() #first 5 lines(by default) out of 506

#adding a new colmn of target values to dataframe
boston['TARGET']=df.target #name of new column appended
boston.head()

#fnctn devides entire data set to training & testing data
from sklearn.model_selection import train_test_split 

# drop the column with name target ,axis=1 drops a column,this is copy of original where original is unchanged
X=boston.drop('TARGET', axis=1) 

#access to last column
Y=boston['TARGET']

#training part eg:guide book given to students and test is what students give
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.15,random_state=5) #15/100 will be in test set on random basis

print(X_train.shape)
print(X_test.shape) #rows,column format
print(Y_train.shape)
print(Y_test.shape)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

#fitting model on training dataset
lin_model=LinearRegression()
lin_model.fit(X_train,Y_train)

y_train_predict=lin_model.predict(X_train)
rmse=(np.sqrt(mean_squared_error(Y_train,y_train_predict)))

print("The model performance for training set")
print('RMSE is{}'.format(rmse))
print("\n")

#on testing set
y_test_predict=lin_model.predict(X_test)
rmse=(np.sqrt(mean_squared_error(Y_test,y_test_predict)))

print("The model performance for testing set")
print('RMSE is{}'.format(rmse))


[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(430, 13)
(76, 13)
(430,)
(76,)
The model performance for training set
RMSE is4.710901797319796


The model performance for testing set
RMSE is4.687543527902972


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.